[package]
name = "mrk"
version = "0.3.0"
edition = "2024"
description = "A minimal markup builder library"
authors = ["Thiago Oliveira <thiago@signaes.com>"]
license = "MIT"
repository = "https://github.com/signaes/mrk"
homepage = "https://github.com/signaes/mrk"
keywords = ["markup", "builder", "html"]
categories = ["template-engine"]

[features]
default = []
html = []

[dependencies]

[package.metadata.docs.rs]
features = ["html"]
